name: Deploy Infra Terraform

on:
  workflow_dispatch:           

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-3
      IMAGE_URI: 380426548948.dkr.ecr.eu-west-3.amazonaws.com/myproject-repo:lambda-20251218090602-fastapi-data-eng-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Authentification AWS via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions

      # Installer Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      # Terraform dans env/dev
      - name: Terraform Init
        working-directory: ./infra/env/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra/env/dev
        run: terraform plan -var="image_uri=${{ env.IMAGE_URI }}"

      - name: Terraform Apply
        working-directory: ./infra/env/dev
        run: terraform apply -auto-approve -var="image_uri=${{ env.IMAGE_URI }}"

      # Afficher les URLs
      - name: Show API URLs
        working-directory: ./infra/env/dev
        run: |
          echo "ðŸš€ API dÃ©ployÃ©e !"
          echo "URL principale : https://$(terraform output -raw api_url)"
          echo "Swagger UI     : https://$(terraform output -raw api_url)/docs"
          echo "OpenAPI JSON   : https://$(terraform output -raw api_url)/openapi.json"