name: Destroy Infra Terraform

on:
  workflow_dispatch:   

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-3
      TF_VAR_env: ${{ secrets.TF_VAR_env }}
      TF_VAR_project_name: ${{ secrets.TF_VAR_project_name }}
      TF_VAR_team: ${{ secrets.TF_VAR_team }}
      TF_VAR_company_name: ${{ secrets.TF_VAR_company_name }}
      TF_VAR_image_uri: 380426548948.dkr.ecr.eu-west-3.amazonaws.com/fastapi-lambda-app:v2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Authentification AWS via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActionsDestroy

      # Installer Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      # Terraform destroy dans env/dev
      - name: Terraform Init
        working-directory: ./infra/env/dev
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./infra/env/dev
        run: terraform destroy -auto-approve
